// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TishiesVeggies.Data;

#nullable disable

namespace TishiesVeggies.Data.Migrations
{
    [DbContext(typeof(TishiesVeggiesDbContext))]
    [Migration("20260802151220_AddCustomFruitNameToLog")]
    partial class AddCustomFruitNameToLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TishiesVeggies.Data.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuickAdd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fruits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Peas"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fruit",
                            IsQuickAdd = true,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Fruit",
                            IsQuickAdd = true,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fruit",
                            IsQuickAdd = true,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fruit",
                            IsQuickAdd = true,
                            Name = "Grapes"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Veggie",
                            IsQuickAdd = true,
                            Name = "Sweetcorn"
                        });
                });

            modelBuilder.Entity("TishiesVeggies.Data.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomFruitName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FruitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FruitId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("TishiesVeggies.Data.Log", b =>
                {
                    b.HasOne("TishiesVeggies.Data.Fruit", "Fruit")
                        .WithMany("Logs")
                        .HasForeignKey("FruitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fruit");
                });

            modelBuilder.Entity("TishiesVeggies.Data.Fruit", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
